CREATE TABLE [dbo].[Cotizacion] (
    [Id]              INT             IDENTITY (1, 1) NOT NULL,
    [EmpresaId]       INT             NOT NULL,
    [ClienteId]       INT             NOT NULL,
    [UsuarioId]       INT             NOT NULL,
    [VendedorId]      INT             NOT NULL,
    [MaterialId]      INT             NOT NULL,
    [TipoCambioId]    INT             NOT NULL,
    [LineaId]         INT             NULL,
    [Fecha]           DATETIME2 (7)   NULL,
    [PrecioUnitario]  DECIMAL (15, 2) NULL,
    [Subtotal]        DECIMAL (15, 2) NULL,
    [Porcentaje]      DECIMAL (15, 2) NULL,
    [TotalUSD]        DECIMAL (15, 2) NULL,
    [TotalCol]        DECIMAL (15, 2) NULL,
    [Cantidad]        INT             NULL,
    [Montaje]         DECIMAL (10, 2) NULL,
    [Base]            DECIMAL (10, 2) NULL,
    [Altura]          DECIMAL (10, 2) NULL,
    [Tintas]          DECIMAL (10, 2) NULL,
    [Cubrimiento]     DECIMAL (10, 2) NULL,
    [Troquel]         DECIMAL (10, 2) NULL,
    [Doblez]          DECIMAL (10, 2) NULL,
    [Cuatricromia]    DECIMAL (10, 2) NULL,
    [Otro]            DECIMAL (10, 2) NULL,
    [PorcEvento]      DECIMAL (10, 2) NULL,
    [Aplicada]        BIT             NULL,
    [FecAplicada]     DATETIME2 (7)   NULL,
    [FecRegistro]     DATETIME2 (7)   NULL,
    [NumPedido]       TEXT            NULL,
    [PrecioMaterial]  DECIMAL (15, 2) NULL,
    [PrecioTintas]    DECIMAL (15, 2) NULL,
    [PrecioArte]      DECIMAL (15, 2) NULL,
    [PrecioImpresion] DECIMAL (15, 2) NULL,
    [PrecioMolde]     DECIMAL (15, 2) NULL,
    [PrecioCorte]     DECIMAL (15, 2) NULL,
    [PrecioPositivo]  DECIMAL (15, 2) NULL,
    [PrecioSolvente]  DECIMAL (15, 2) NULL,
    [Rendimiento]     DECIMAL (10, 2) NULL,
    [Laminas]         DECIMAL (10, 2) NULL,
    [Observacion]     TEXT            NULL,
    [DivLargo]        DECIMAL (10, 2) NULL,
    [DivAncho]        DECIMAL (10, 2) NULL,
    [Activo]          BIT             DEFAULT ((1)) NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC),
    FOREIGN KEY ([ClienteId]) REFERENCES [dbo].[Cliente] ([Id]),
    FOREIGN KEY ([EmpresaId]) REFERENCES [dbo].[Empresa] ([Id]),
    FOREIGN KEY ([MaterialId]) REFERENCES [dbo].[Material] ([Id]),
    FOREIGN KEY ([TipoCambioId]) REFERENCES [dbo].[TipoCambio] ([Id]),
    FOREIGN KEY ([UsuarioId]) REFERENCES [dbo].[Usuario] ([Id]),
    FOREIGN KEY ([VendedorId]) REFERENCES [dbo].[Vendedor] ([Id])
);

